name: Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: Linter
        run: yarn lint
